name: CI for Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Create .env file from GitHub Secrets
        run: |
          echo "STACK_VERSION=${{ secrets.STACK_VERSION }}" >> .env
          echo "ES_PORT=${{ secrets.ES_PORT }}" >> .env
          echo "KIBANA_PORT=${{ secrets.KIBANA_PORT }}" >> .env
          echo "ELASTIC_PASSWORD=${{ secrets.ELASTIC_PASSWORD }}" >> .env
          echo "KIBANA_PASSWORD=${{ secrets.KIBANA_PASSWORD }}" >> .env
          echo "LICENSE=${{ secrets.LICENSE }}" >> .env
          echo "CLUSTER_NAME=${{ secrets.CLUSTER_NAME }}" >> .env
          echo "ENCRYPTION_KEY=${{ secrets.ENCRYPTION_KEY }}" >> .env
          echo "ES_MEM_LIMIT=${{ secrets.ES_MEM_LIMIT }}" >> .env
          echo "KB_MEM_LIMIT=${{ secrets.KB_MEM_LIMIT }}" >> .env
          echo "LS_MEM_LIMIT=${{ secrets.LS_MEM_LIMIT }}" >> .env

      - name: Build and run Docker Compose
        run: docker-compose up -d --build

      - name: Wait for services to be healthy
        run: |
          echo "Waiting for services to be healthy..."
          sleep 60  # Adjust the sleep time as needed

      - name: Check if Elasticsearch is running
        run: |
          if [ $(docker inspect -f '{{.State.Running}}' $(docker-compose ps -q es01)) = "false" ]; then
            echo "Elasticsearch is not running correctly."
            exit 1
          else
            echo "Elasticsearch is running correctly."
          fi

      - name: Check if Kibana is running
        run: |
          if [ $(docker inspect -f '{{.State.Running}}' $(docker-compose ps -q kibana)) = "false" ]; then
            echo "Kibana is not running correctly."
            exit 1
          else
            echo "Kibana is running correctly."
          fi

      - name: Check if Logstash is running
        run: |
          if [ $(docker inspect -f '{{.State.Running}}' $(docker-compose ps -q logstash01)) = "false" ]; then
            echo "Logstash is not running correctly."
            exit 1
          else
            echo "Logstash is running correctly."
          fi

      - name: Stop Docker Compose
        run: docker-compose down
